// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdvanceDaysArgs {
    pub days: u64,
}

impl From<AdvanceDaysArgs> for super::Reducer {
    fn from(args: AdvanceDaysArgs) -> Self {
        Self::AdvanceDays {
            days: args.days,
}
}
}

impl __sdk::InModule for AdvanceDaysArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `advance_days`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait advance_days {
    /// Request that the remote module invoke the reducer `advance_days` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`advance_days:advance_days_then`] to run a callback after the reducer completes.
    fn advance_days(&self, days: u64,
) -> __sdk::Result<()> {
        self.advance_days_then(days,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `advance_days` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn advance_days_then(
        &self,
        days: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl advance_days for super::RemoteReducers {
    fn advance_days_then(
        &self,
        days: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AdvanceDaysArgs { days,  }, callback)
    }
}

