// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdvanceTicksArgs {
    pub num_ticks: u64,
}

impl From<AdvanceTicksArgs> for super::Reducer {
    fn from(args: AdvanceTicksArgs) -> Self {
        Self::AdvanceTicks {
            num_ticks: args.num_ticks,
}
}
}

impl __sdk::InModule for AdvanceTicksArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `advance_ticks`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait advance_ticks {
    /// Request that the remote module invoke the reducer `advance_ticks` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`advance_ticks:advance_ticks_then`] to run a callback after the reducer completes.
    fn advance_ticks(&self, num_ticks: u64,
) -> __sdk::Result<()> {
        self.advance_ticks_then(num_ticks,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `advance_ticks` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn advance_ticks_then(
        &self,
        num_ticks: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl advance_ticks for super::RemoteReducers {
    fn advance_ticks_then(
        &self,
        num_ticks: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AdvanceTicksArgs { num_ticks,  }, callback)
    }
}

