// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CombatEvent {
    pub id: u64,
    pub tick: u64,
    pub system_id: u64,
    pub attacker_ship_id: u64,
    pub defender_ship_id: u64,
    pub attacker_faction_id: u64,
    pub defender_faction_id: u64,
    pub damage_dealt: i64,
    pub destroyed: bool,
}


impl __sdk::InModule for CombatEvent {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `CombatEvent`.
///
/// Provides typed access to columns for query building.
pub struct CombatEventCols {
    pub id: __sdk::__query_builder::Col<CombatEvent, u64>,
    pub tick: __sdk::__query_builder::Col<CombatEvent, u64>,
    pub system_id: __sdk::__query_builder::Col<CombatEvent, u64>,
    pub attacker_ship_id: __sdk::__query_builder::Col<CombatEvent, u64>,
    pub defender_ship_id: __sdk::__query_builder::Col<CombatEvent, u64>,
    pub attacker_faction_id: __sdk::__query_builder::Col<CombatEvent, u64>,
    pub defender_faction_id: __sdk::__query_builder::Col<CombatEvent, u64>,
    pub damage_dealt: __sdk::__query_builder::Col<CombatEvent, i64>,
    pub destroyed: __sdk::__query_builder::Col<CombatEvent, bool>,
}

impl __sdk::__query_builder::HasCols for CombatEvent {
    type Cols = CombatEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CombatEventCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            tick: __sdk::__query_builder::Col::new(table_name, "tick"),
            system_id: __sdk::__query_builder::Col::new(table_name, "system_id"),
            attacker_ship_id: __sdk::__query_builder::Col::new(table_name, "attacker_ship_id"),
            defender_ship_id: __sdk::__query_builder::Col::new(table_name, "defender_ship_id"),
            attacker_faction_id: __sdk::__query_builder::Col::new(table_name, "attacker_faction_id"),
            defender_faction_id: __sdk::__query_builder::Col::new(table_name, "defender_faction_id"),
            damage_dealt: __sdk::__query_builder::Col::new(table_name, "damage_dealt"),
            destroyed: __sdk::__query_builder::Col::new(table_name, "destroyed"),

        }
    }
}

/// Indexed column accessor struct for the table `CombatEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct CombatEventIxCols {
    pub id: __sdk::__query_builder::IxCol<CombatEvent, u64>,
    pub tick: __sdk::__query_builder::IxCol<CombatEvent, u64>,
}

impl __sdk::__query_builder::HasIxCols for CombatEvent {
    type IxCols = CombatEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CombatEventIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            tick: __sdk::__query_builder::IxCol::new(table_name, "tick"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CombatEvent {}

