// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CommitDesignArgs {
    pub draft_id: u64,
    pub name: String,
}

impl From<CommitDesignArgs> for super::Reducer {
    fn from(args: CommitDesignArgs) -> Self {
        Self::CommitDesign {
            draft_id: args.draft_id,
            name: args.name,
}
}
}

impl __sdk::InModule for CommitDesignArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `commit_design`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait commit_design {
    /// Request that the remote module invoke the reducer `commit_design` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`commit_design:commit_design_then`] to run a callback after the reducer completes.
    fn commit_design(&self, draft_id: u64,
name: String,
) -> __sdk::Result<()> {
        self.commit_design_then(draft_id, name,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `commit_design` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn commit_design_then(
        &self,
        draft_id: u64,
name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl commit_design for super::RemoteReducers {
    fn commit_design_then(
        &self,
        draft_id: u64,
name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(CommitDesignArgs { draft_id, name,  }, callback)
    }
}

