// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateDraftArgs {
    pub faction_id: u64,
    pub name: String,
}

impl From<CreateDraftArgs> for super::Reducer {
    fn from(args: CreateDraftArgs) -> Self {
        Self::CreateDraft {
            faction_id: args.faction_id,
            name: args.name,
}
}
}

impl __sdk::InModule for CreateDraftArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_draft`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_draft {
    /// Request that the remote module invoke the reducer `create_draft` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_draft:create_draft_then`] to run a callback after the reducer completes.
    fn create_draft(&self, faction_id: u64,
name: String,
) -> __sdk::Result<()> {
        self.create_draft_then(faction_id, name,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_draft` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_draft_then(
        &self,
        faction_id: u64,
name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_draft for super::RemoteReducers {
    fn create_draft_then(
        &self,
        faction_id: u64,
name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(CreateDraftArgs { faction_id, name,  }, callback)
    }
}

