// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::faction_type::Faction;

/// Table handle for the table `faction`.
///
/// Obtain a handle from the [`FactionTableAccess::faction`] method on [`super::RemoteTables`],
/// like `ctx.db.faction()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.faction().on_insert(...)`.
pub struct FactionTableHandle<'ctx> {
    imp: __sdk::TableHandle<Faction>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `faction`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FactionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FactionTableHandle`], which mediates access to the table `faction`.
    fn faction(&self) -> FactionTableHandle<'_>;
}

impl FactionTableAccess for super::RemoteTables {
    fn faction(&self) -> FactionTableHandle<'_> {
        FactionTableHandle {
            imp: self.imp.get_table::<Faction>("faction"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FactionInsertCallbackId(__sdk::CallbackId);
pub struct FactionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for FactionTableHandle<'ctx> {
    type Row = Faction;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = Faction> + '_ { self.imp.iter() }

    type InsertCallbackId = FactionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FactionInsertCallbackId {
        FactionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FactionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FactionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FactionDeleteCallbackId {
        FactionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FactionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct FactionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FactionTableHandle<'ctx> {
    type UpdateCallbackId = FactionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FactionUpdateCallbackId {
        FactionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FactionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `id` unique index on the table `faction`,
        /// which allows point queries on the field of the same name
        /// via the [`FactionIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.faction().id().find(...)`.
        pub struct FactionIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<Faction, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> FactionTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `faction`.
            pub fn id(&self) -> FactionIdUnique<'ctx> {
                FactionIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> FactionIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<Faction> {
                self.imp.find(col_val)
            }
        }
        
        /// Access to the `name` unique index on the table `faction`,
        /// which allows point queries on the field of the same name
        /// via the [`FactionNameUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.faction().name().find(...)`.
        pub struct FactionNameUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<Faction, String>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> FactionTableHandle<'ctx> {
            /// Get a handle on the `name` unique index on the table `faction`.
            pub fn name(&self) -> FactionNameUnique<'ctx> {
                FactionNameUnique {
                    imp: self.imp.get_unique_constraint::<String>("name"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> FactionNameUnique<'ctx> {
            /// Find the subscribed row whose `name` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &String) -> Option<Faction> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<Faction>("faction");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Faction>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<Faction>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `Faction`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait factionQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `Faction`.
            fn faction(&self) -> __sdk::__query_builder::Table<Faction>;
        }

        impl factionQueryTableAccess for __sdk::QueryTableAccessor {
            fn faction(&self) -> __sdk::__query_builder::Table<Faction> {
                __sdk::__query_builder::Table::new("faction")
            }
        }

