// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Faction {
    pub id: u64,
    pub name: String,
    pub is_ai: bool,
    pub minerals: i64,
    pub energy: i64,
    pub research: i64,
    pub home_system_id: u64,
}


impl __sdk::InModule for Faction {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `Faction`.
///
/// Provides typed access to columns for query building.
pub struct FactionCols {
    pub id: __sdk::__query_builder::Col<Faction, u64>,
    pub name: __sdk::__query_builder::Col<Faction, String>,
    pub is_ai: __sdk::__query_builder::Col<Faction, bool>,
    pub minerals: __sdk::__query_builder::Col<Faction, i64>,
    pub energy: __sdk::__query_builder::Col<Faction, i64>,
    pub research: __sdk::__query_builder::Col<Faction, i64>,
    pub home_system_id: __sdk::__query_builder::Col<Faction, u64>,
}

impl __sdk::__query_builder::HasCols for Faction {
    type Cols = FactionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        FactionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            is_ai: __sdk::__query_builder::Col::new(table_name, "is_ai"),
            minerals: __sdk::__query_builder::Col::new(table_name, "minerals"),
            energy: __sdk::__query_builder::Col::new(table_name, "energy"),
            research: __sdk::__query_builder::Col::new(table_name, "research"),
            home_system_id: __sdk::__query_builder::Col::new(table_name, "home_system_id"),

        }
    }
}

/// Indexed column accessor struct for the table `Faction`.
///
/// Provides typed access to indexed columns for query building.
pub struct FactionIxCols {
    pub id: __sdk::__query_builder::IxCol<Faction, u64>,
    pub name: __sdk::__query_builder::IxCol<Faction, String>,
}

impl __sdk::__query_builder::HasIxCols for Faction {
    type IxCols = FactionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        FactionIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Faction {}

