// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct FleetShip {
    pub ship_id: u64,
    pub fleet_id: u64,
}


impl __sdk::InModule for FleetShip {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `FleetShip`.
///
/// Provides typed access to columns for query building.
pub struct FleetShipCols {
    pub ship_id: __sdk::__query_builder::Col<FleetShip, u64>,
    pub fleet_id: __sdk::__query_builder::Col<FleetShip, u64>,
}

impl __sdk::__query_builder::HasCols for FleetShip {
    type Cols = FleetShipCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        FleetShipCols {
            ship_id: __sdk::__query_builder::Col::new(table_name, "ship_id"),
            fleet_id: __sdk::__query_builder::Col::new(table_name, "fleet_id"),

        }
    }
}

/// Indexed column accessor struct for the table `FleetShip`.
///
/// Provides typed access to indexed columns for query building.
pub struct FleetShipIxCols {
    pub fleet_id: __sdk::__query_builder::IxCol<FleetShip, u64>,
    pub ship_id: __sdk::__query_builder::IxCol<FleetShip, u64>,
}

impl __sdk::__query_builder::HasIxCols for FleetShip {
    type IxCols = FleetShipIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        FleetShipIxCols {
            fleet_id: __sdk::__query_builder::IxCol::new(table_name, "fleet_id"),
            ship_id: __sdk::__query_builder::IxCol::new(table_name, "ship_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for FleetShip {}

