// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::fleet_ship_type::FleetShip;

/// Table handle for the table `fleet_ship`.
///
/// Obtain a handle from the [`FleetShipTableAccess::fleet_ship`] method on [`super::RemoteTables`],
/// like `ctx.db.fleet_ship()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.fleet_ship().on_insert(...)`.
pub struct FleetShipTableHandle<'ctx> {
    imp: __sdk::TableHandle<FleetShip>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `fleet_ship`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FleetShipTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FleetShipTableHandle`], which mediates access to the table `fleet_ship`.
    fn fleet_ship(&self) -> FleetShipTableHandle<'_>;
}

impl FleetShipTableAccess for super::RemoteTables {
    fn fleet_ship(&self) -> FleetShipTableHandle<'_> {
        FleetShipTableHandle {
            imp: self.imp.get_table::<FleetShip>("fleet_ship"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FleetShipInsertCallbackId(__sdk::CallbackId);
pub struct FleetShipDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for FleetShipTableHandle<'ctx> {
    type Row = FleetShip;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = FleetShip> + '_ { self.imp.iter() }

    type InsertCallbackId = FleetShipInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FleetShipInsertCallbackId {
        FleetShipInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FleetShipInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FleetShipDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FleetShipDeleteCallbackId {
        FleetShipDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FleetShipDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct FleetShipUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FleetShipTableHandle<'ctx> {
    type UpdateCallbackId = FleetShipUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FleetShipUpdateCallbackId {
        FleetShipUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FleetShipUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `ship_id` unique index on the table `fleet_ship`,
        /// which allows point queries on the field of the same name
        /// via the [`FleetShipShipIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.fleet_ship().ship_id().find(...)`.
        pub struct FleetShipShipIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<FleetShip, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> FleetShipTableHandle<'ctx> {
            /// Get a handle on the `ship_id` unique index on the table `fleet_ship`.
            pub fn ship_id(&self) -> FleetShipShipIdUnique<'ctx> {
                FleetShipShipIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("ship_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> FleetShipShipIdUnique<'ctx> {
            /// Find the subscribed row whose `ship_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<FleetShip> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<FleetShip>("fleet_ship");
    _table.add_unique_constraint::<u64>("ship_id", |row| &row.ship_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<FleetShip>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<FleetShip>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `FleetShip`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait fleet_shipQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `FleetShip`.
            fn fleet_ship(&self) -> __sdk::__query_builder::Table<FleetShip>;
        }

        impl fleet_shipQueryTableAccess for __sdk::QueryTableAccessor {
            fn fleet_ship(&self) -> __sdk::__query_builder::Table<FleetShip> {
                __sdk::__query_builder::Table::new("fleet_ship")
            }
        }

