// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Fleet {
    pub id: u64,
    pub faction_id: u64,
    pub system_id: u64,
    pub name: String,
    pub dest_system_id: Option::<u64>,
    pub arrival_tick: Option::<u64>,
}


impl __sdk::InModule for Fleet {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `Fleet`.
///
/// Provides typed access to columns for query building.
pub struct FleetCols {
    pub id: __sdk::__query_builder::Col<Fleet, u64>,
    pub faction_id: __sdk::__query_builder::Col<Fleet, u64>,
    pub system_id: __sdk::__query_builder::Col<Fleet, u64>,
    pub name: __sdk::__query_builder::Col<Fleet, String>,
    pub dest_system_id: __sdk::__query_builder::Col<Fleet, Option::<u64>>,
    pub arrival_tick: __sdk::__query_builder::Col<Fleet, Option::<u64>>,
}

impl __sdk::__query_builder::HasCols for Fleet {
    type Cols = FleetCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        FleetCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            faction_id: __sdk::__query_builder::Col::new(table_name, "faction_id"),
            system_id: __sdk::__query_builder::Col::new(table_name, "system_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            dest_system_id: __sdk::__query_builder::Col::new(table_name, "dest_system_id"),
            arrival_tick: __sdk::__query_builder::Col::new(table_name, "arrival_tick"),

        }
    }
}

/// Indexed column accessor struct for the table `Fleet`.
///
/// Provides typed access to indexed columns for query building.
pub struct FleetIxCols {
    pub faction_id: __sdk::__query_builder::IxCol<Fleet, u64>,
    pub id: __sdk::__query_builder::IxCol<Fleet, u64>,
    pub system_id: __sdk::__query_builder::IxCol<Fleet, u64>,
}

impl __sdk::__query_builder::HasIxCols for Fleet {
    type IxCols = FleetIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        FleetIxCols {
            faction_id: __sdk::__query_builder::IxCol::new(table_name, "faction_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            system_id: __sdk::__query_builder::IxCol::new(table_name, "system_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Fleet {}

