// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::game_state_type::GameState;

/// Table handle for the table `game_state`.
///
/// Obtain a handle from the [`GameStateTableAccess::game_state`] method on [`super::RemoteTables`],
/// like `ctx.db.game_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_state().on_insert(...)`.
pub struct GameStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<GameState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameStateTableHandle`], which mediates access to the table `game_state`.
    fn game_state(&self) -> GameStateTableHandle<'_>;
}

impl GameStateTableAccess for super::RemoteTables {
    fn game_state(&self) -> GameStateTableHandle<'_> {
        GameStateTableHandle {
            imp: self.imp.get_table::<GameState>("game_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameStateInsertCallbackId(__sdk::CallbackId);
pub struct GameStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GameStateTableHandle<'ctx> {
    type Row = GameState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = GameState> + '_ { self.imp.iter() }

    type InsertCallbackId = GameStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameStateInsertCallbackId {
        GameStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameStateDeleteCallbackId {
        GameStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameStateTableHandle<'ctx> {
    type UpdateCallbackId = GameStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameStateUpdateCallbackId {
        GameStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `id` unique index on the table `game_state`,
        /// which allows point queries on the field of the same name
        /// via the [`GameStateIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.game_state().id().find(...)`.
        pub struct GameStateIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<GameState, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> GameStateTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `game_state`.
            pub fn id(&self) -> GameStateIdUnique<'ctx> {
                GameStateIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> GameStateIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<GameState> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<GameState>("game_state");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GameState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<GameState>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `GameState`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait game_stateQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `GameState`.
            fn game_state(&self) -> __sdk::__query_builder::Table<GameState>;
        }

        impl game_stateQueryTableAccess for __sdk::QueryTableAccessor {
            fn game_state(&self) -> __sdk::__query_builder::Table<GameState> {
                __sdk::__query_builder::Table::new("game_state")
            }
        }

