// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GameState {
    pub id: u64,
    pub current_tick: u64,
    pub rng_seed: u64,
    pub schema_version: u32,
}


impl __sdk::InModule for GameState {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `GameState`.
///
/// Provides typed access to columns for query building.
pub struct GameStateCols {
    pub id: __sdk::__query_builder::Col<GameState, u64>,
    pub current_tick: __sdk::__query_builder::Col<GameState, u64>,
    pub rng_seed: __sdk::__query_builder::Col<GameState, u64>,
    pub schema_version: __sdk::__query_builder::Col<GameState, u32>,
}

impl __sdk::__query_builder::HasCols for GameState {
    type Cols = GameStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GameStateCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            current_tick: __sdk::__query_builder::Col::new(table_name, "current_tick"),
            rng_seed: __sdk::__query_builder::Col::new(table_name, "rng_seed"),
            schema_version: __sdk::__query_builder::Col::new(table_name, "schema_version"),

        }
    }
}

/// Indexed column accessor struct for the table `GameState`.
///
/// Provides typed access to indexed columns for query building.
pub struct GameStateIxCols {
    pub id: __sdk::__query_builder::IxCol<GameState, u64>,
}

impl __sdk::__query_builder::HasIxCols for GameState {
    type IxCols = GameStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GameStateIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GameState {}

