// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.3.0 (commit aa73d1c35b4b346b98eeba10a3d756b4ae72162f).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

pub mod block_type_type;
pub mod combat_event_type;
pub mod faction_type;
pub mod fleet_type;
pub mod fleet_ship_type;
pub mod game_state_type;
pub mod order_type;
pub mod order_status_type;
pub mod order_type_type;
pub mod planet_type;
pub mod player_account_type;
pub mod ship_type;
pub mod ship_design_type;
pub mod ship_design_block_type;
pub mod ship_design_draft_type;
pub mod ship_design_draft_block_type;
pub mod sim_run_type;
pub mod star_system_type;
pub mod tick_timer_type;
pub mod advance_days_reducer;
pub mod advance_ticks_reducer;
pub mod create_faction_reducer;
pub mod combat_event_table;
pub mod faction_table;
pub mod fleet_table;
pub mod fleet_ship_table;
pub mod game_state_table;
pub mod orders_table;
pub mod planet_table;
pub mod player_account_table;
pub mod ship_table;
pub mod ship_design_table;
pub mod ship_design_block_table;
pub mod ship_design_draft_table;
pub mod ship_design_draft_block_table;
pub mod sim_run_table;
pub mod star_system_table;
pub mod tick_timer_table;

pub use block_type_type::BlockType;
pub use combat_event_type::CombatEvent;
pub use faction_type::Faction;
pub use fleet_type::Fleet;
pub use fleet_ship_type::FleetShip;
pub use game_state_type::GameState;
pub use order_type::Order;
pub use order_status_type::OrderStatus;
pub use order_type_type::OrderType;
pub use planet_type::Planet;
pub use player_account_type::PlayerAccount;
pub use ship_type::Ship;
pub use ship_design_type::ShipDesign;
pub use ship_design_block_type::ShipDesignBlock;
pub use ship_design_draft_type::ShipDesignDraft;
pub use ship_design_draft_block_type::ShipDesignDraftBlock;
pub use sim_run_type::SimRun;
pub use star_system_type::StarSystem;
pub use tick_timer_type::TickTimer;
pub use combat_event_table::*;
pub use faction_table::*;
pub use fleet_table::*;
pub use fleet_ship_table::*;
pub use game_state_table::*;
pub use orders_table::*;
pub use planet_table::*;
pub use player_account_table::*;
pub use ship_table::*;
pub use ship_design_table::*;
pub use ship_design_block_table::*;
pub use ship_design_draft_table::*;
pub use ship_design_draft_block_table::*;
pub use sim_run_table::*;
pub use star_system_table::*;
pub use tick_timer_table::*;
pub use advance_days_reducer::advance_days;
pub use advance_ticks_reducer::advance_ticks;
pub use create_faction_reducer::create_faction;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
        AdvanceDays {
        days: u64,
}    ,
    AdvanceTicks {
        num_ticks: u64,
}    ,
    CreateFaction {
        name: String,
}    ,
}


impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
                        Reducer::AdvanceDays { .. } => "advance_days",
            Reducer::AdvanceTicks { .. } => "advance_ticks",
            Reducer::CreateFaction { .. } => "create_faction",
            _ => unreachable!(),
}
}
    #[allow(clippy::clone_on_copy)]
fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
                        Reducer::AdvanceDays{
                days,
}             => __sats::bsatn::to_vec(&advance_days_reducer::AdvanceDaysArgs {
                days: days.clone(),
}),
            Reducer::AdvanceTicks{
                num_ticks,
}             => __sats::bsatn::to_vec(&advance_ticks_reducer::AdvanceTicksArgs {
                num_ticks: num_ticks.clone(),
}),
            Reducer::CreateFaction{
                name,
}             => __sats::bsatn::to_vec(&create_faction_reducer::CreateFactionArgs {
                name: name.clone(),
}),
            _ => unreachable!(),
}
}
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
        combat_event: __sdk::TableUpdate<CombatEvent>,
    faction: __sdk::TableUpdate<Faction>,
    fleet: __sdk::TableUpdate<Fleet>,
    fleet_ship: __sdk::TableUpdate<FleetShip>,
    game_state: __sdk::TableUpdate<GameState>,
    orders: __sdk::TableUpdate<Order>,
    planet: __sdk::TableUpdate<Planet>,
    player_account: __sdk::TableUpdate<PlayerAccount>,
    ship: __sdk::TableUpdate<Ship>,
    ship_design: __sdk::TableUpdate<ShipDesign>,
    ship_design_block: __sdk::TableUpdate<ShipDesignBlock>,
    ship_design_draft: __sdk::TableUpdate<ShipDesignDraft>,
    ship_design_draft_block: __sdk::TableUpdate<ShipDesignDraftBlock>,
    sim_run: __sdk::TableUpdate<SimRun>,
    star_system: __sdk::TableUpdate<StarSystem>,
    tick_timer: __sdk::TableUpdate<TickTimer>,
}


impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {

        "combat_event" => db_update.combat_event.append(combat_event_table::parse_table_update(table_update)?),
    "faction" => db_update.faction.append(faction_table::parse_table_update(table_update)?),
    "fleet" => db_update.fleet.append(fleet_table::parse_table_update(table_update)?),
    "fleet_ship" => db_update.fleet_ship.append(fleet_ship_table::parse_table_update(table_update)?),
    "game_state" => db_update.game_state.append(game_state_table::parse_table_update(table_update)?),
    "orders" => db_update.orders.append(orders_table::parse_table_update(table_update)?),
    "planet" => db_update.planet.append(planet_table::parse_table_update(table_update)?),
    "player_account" => db_update.player_account.append(player_account_table::parse_table_update(table_update)?),
    "ship" => db_update.ship.append(ship_table::parse_table_update(table_update)?),
    "ship_design" => db_update.ship_design.append(ship_design_table::parse_table_update(table_update)?),
    "ship_design_block" => db_update.ship_design_block.append(ship_design_block_table::parse_table_update(table_update)?),
    "ship_design_draft" => db_update.ship_design_draft.append(ship_design_draft_table::parse_table_update(table_update)?),
    "ship_design_draft_block" => db_update.ship_design_draft_block.append(ship_design_draft_block_table::parse_table_update(table_update)?),
    "sim_run" => db_update.sim_run.append(sim_run_table::parse_table_update(table_update)?),
    "star_system" => db_update.star_system.append(star_system_table::parse_table_update(table_update)?),
    "tick_timer" => db_update.tick_timer.append(tick_timer_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    ).into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(&self, cache: &mut __sdk::ClientCache<RemoteModule>) -> AppliedDiff<'_> {
                    let mut diff = AppliedDiff::default();
                
                diff.combat_event = cache.apply_diff_to_table::<CombatEvent>("combat_event", &self.combat_event).with_updates_by_pk(|row| &row.id);
        diff.faction = cache.apply_diff_to_table::<Faction>("faction", &self.faction).with_updates_by_pk(|row| &row.id);
        diff.fleet = cache.apply_diff_to_table::<Fleet>("fleet", &self.fleet).with_updates_by_pk(|row| &row.id);
        diff.fleet_ship = cache.apply_diff_to_table::<FleetShip>("fleet_ship", &self.fleet_ship).with_updates_by_pk(|row| &row.ship_id);
        diff.game_state = cache.apply_diff_to_table::<GameState>("game_state", &self.game_state).with_updates_by_pk(|row| &row.id);
        diff.orders = cache.apply_diff_to_table::<Order>("orders", &self.orders).with_updates_by_pk(|row| &row.id);
        diff.planet = cache.apply_diff_to_table::<Planet>("planet", &self.planet).with_updates_by_pk(|row| &row.id);
        diff.player_account = cache.apply_diff_to_table::<PlayerAccount>("player_account", &self.player_account).with_updates_by_pk(|row| &row.identity);
        diff.ship = cache.apply_diff_to_table::<Ship>("ship", &self.ship).with_updates_by_pk(|row| &row.id);
        diff.ship_design = cache.apply_diff_to_table::<ShipDesign>("ship_design", &self.ship_design).with_updates_by_pk(|row| &row.id);
        diff.ship_design_block = cache.apply_diff_to_table::<ShipDesignBlock>("ship_design_block", &self.ship_design_block).with_updates_by_pk(|row| &row.id);
        diff.ship_design_draft = cache.apply_diff_to_table::<ShipDesignDraft>("ship_design_draft", &self.ship_design_draft).with_updates_by_pk(|row| &row.id);
        diff.ship_design_draft_block = cache.apply_diff_to_table::<ShipDesignDraftBlock>("ship_design_draft_block", &self.ship_design_draft_block).with_updates_by_pk(|row| &row.id);
        diff.sim_run = cache.apply_diff_to_table::<SimRun>("sim_run", &self.sim_run).with_updates_by_pk(|row| &row.run_id);
        diff.star_system = cache.apply_diff_to_table::<StarSystem>("star_system", &self.star_system).with_updates_by_pk(|row| &row.id);
        diff.tick_timer = cache.apply_diff_to_table::<TickTimer>("tick_timer", &self.tick_timer).with_updates_by_pk(|row| &row.scheduled_id);

                    diff
                }
fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
                let mut db_update = DbUpdate::default();
for table_rows in raw.tables {
            match &table_rows.table[..] {
                                "combat_event" => db_update.combat_event.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "faction" => db_update.faction.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "fleet" => db_update.fleet.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "fleet_ship" => db_update.fleet_ship.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "game_state" => db_update.game_state.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "orders" => db_update.orders.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "planet" => db_update.planet.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player_account" => db_update.player_account.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ship" => db_update.ship.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ship_design" => db_update.ship_design.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ship_design_block" => db_update.ship_design_block.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ship_design_draft" => db_update.ship_design_draft.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ship_design_draft_block" => db_update.ship_design_draft_block.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "sim_run" => db_update.sim_run.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "star_system" => db_update.star_system.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "tick_timer" => db_update.tick_timer.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => { return Err(__sdk::InternalError::unknown_name("table", unknown, "QueryRows").into()); }
}}        Ok(db_update)
}
fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
                let mut db_update = DbUpdate::default();
for table_rows in raw.tables {
            match &table_rows.table[..] {
                                "combat_event" => db_update.combat_event.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "faction" => db_update.faction.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "fleet" => db_update.fleet.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "fleet_ship" => db_update.fleet_ship.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "game_state" => db_update.game_state.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "orders" => db_update.orders.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "planet" => db_update.planet.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player_account" => db_update.player_account.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ship" => db_update.ship.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ship_design" => db_update.ship_design.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ship_design_block" => db_update.ship_design_block.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ship_design_draft" => db_update.ship_design_draft.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ship_design_draft_block" => db_update.ship_design_draft_block.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "sim_run" => db_update.sim_run.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "star_system" => db_update.star_system.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "tick_timer" => db_update.tick_timer.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => { return Err(__sdk::InternalError::unknown_name("table", unknown, "QueryRows").into()); }
}}        Ok(db_update)
}
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
        combat_event: __sdk::TableAppliedDiff<'r, CombatEvent>,
    faction: __sdk::TableAppliedDiff<'r, Faction>,
    fleet: __sdk::TableAppliedDiff<'r, Fleet>,
    fleet_ship: __sdk::TableAppliedDiff<'r, FleetShip>,
    game_state: __sdk::TableAppliedDiff<'r, GameState>,
    orders: __sdk::TableAppliedDiff<'r, Order>,
    planet: __sdk::TableAppliedDiff<'r, Planet>,
    player_account: __sdk::TableAppliedDiff<'r, PlayerAccount>,
    ship: __sdk::TableAppliedDiff<'r, Ship>,
    ship_design: __sdk::TableAppliedDiff<'r, ShipDesign>,
    ship_design_block: __sdk::TableAppliedDiff<'r, ShipDesignBlock>,
    ship_design_draft: __sdk::TableAppliedDiff<'r, ShipDesignDraft>,
    ship_design_draft_block: __sdk::TableAppliedDiff<'r, ShipDesignDraftBlock>,
    sim_run: __sdk::TableAppliedDiff<'r, SimRun>,
    star_system: __sdk::TableAppliedDiff<'r, StarSystem>,
    tick_timer: __sdk::TableAppliedDiff<'r, TickTimer>,
    __unused: std::marker::PhantomData<&'r ()>,
}


impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(&self, event: &EventContext, callbacks: &mut __sdk::DbCallbacks<RemoteModule>) {
                callbacks.invoke_table_row_callbacks::<CombatEvent>("combat_event", &self.combat_event, event);
        callbacks.invoke_table_row_callbacks::<Faction>("faction", &self.faction, event);
        callbacks.invoke_table_row_callbacks::<Fleet>("fleet", &self.fleet, event);
        callbacks.invoke_table_row_callbacks::<FleetShip>("fleet_ship", &self.fleet_ship, event);
        callbacks.invoke_table_row_callbacks::<GameState>("game_state", &self.game_state, event);
        callbacks.invoke_table_row_callbacks::<Order>("orders", &self.orders, event);
        callbacks.invoke_table_row_callbacks::<Planet>("planet", &self.planet, event);
        callbacks.invoke_table_row_callbacks::<PlayerAccount>("player_account", &self.player_account, event);
        callbacks.invoke_table_row_callbacks::<Ship>("ship", &self.ship, event);
        callbacks.invoke_table_row_callbacks::<ShipDesign>("ship_design", &self.ship_design, event);
        callbacks.invoke_table_row_callbacks::<ShipDesignBlock>("ship_design_block", &self.ship_design_block, event);
        callbacks.invoke_table_row_callbacks::<ShipDesignDraft>("ship_design_draft", &self.ship_design_draft, event);
        callbacks.invoke_table_row_callbacks::<ShipDesignDraftBlock>("ship_design_draft_block", &self.ship_design_draft_block, event);
        callbacks.invoke_table_row_callbacks::<SimRun>("sim_run", &self.sim_run, event);
        callbacks.invoke_table_row_callbacks::<StarSystem>("star_system", &self.star_system, event);
        callbacks.invoke_table_row_callbacks::<TickTimer>("tick_timer", &self.tick_timer, event);
}
}


#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(target_arch = "wasm32", doc = "- [`DbConnection::run_background_task`].")]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(not(target_arch =  "wasm32"), doc = "- [`DbConnection::advance_one_message_blocking`].")]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }

}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext: __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
> {}
impl<Ctx: __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>> RemoteDbContext for Ctx {}


/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
                combat_event_table::register_table(client_cache);
        faction_table::register_table(client_cache);
        fleet_table::register_table(client_cache);
        fleet_ship_table::register_table(client_cache);
        game_state_table::register_table(client_cache);
        orders_table::register_table(client_cache);
        planet_table::register_table(client_cache);
        player_account_table::register_table(client_cache);
        ship_table::register_table(client_cache);
        ship_design_table::register_table(client_cache);
        ship_design_block_table::register_table(client_cache);
        ship_design_draft_table::register_table(client_cache);
        ship_design_draft_block_table::register_table(client_cache);
        sim_run_table::register_table(client_cache);
        star_system_table::register_table(client_cache);
        tick_timer_table::register_table(client_cache);
}
const ALL_TABLE_NAMES: &'static [&'static str] = &[
                "combat_event",
        "faction",
        "fleet",
        "fleet_ship",
        "game_state",
        "orders",
        "planet",
        "player_account",
        "ship",
        "ship_design",
        "ship_design_block",
        "ship_design_draft",
        "ship_design_draft_block",
        "sim_run",
        "star_system",
        "tick_timer",
];
}
