// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct OrderBuildShipArgs {
    pub design_id: u64,
    pub fleet_id: u64,
}

impl From<OrderBuildShipArgs> for super::Reducer {
    fn from(args: OrderBuildShipArgs) -> Self {
        Self::OrderBuildShip {
            design_id: args.design_id,
            fleet_id: args.fleet_id,
}
}
}

impl __sdk::InModule for OrderBuildShipArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `order_build_ship`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait order_build_ship {
    /// Request that the remote module invoke the reducer `order_build_ship` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`order_build_ship:order_build_ship_then`] to run a callback after the reducer completes.
    fn order_build_ship(&self, design_id: u64,
fleet_id: u64,
) -> __sdk::Result<()> {
        self.order_build_ship_then(design_id, fleet_id,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `order_build_ship` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn order_build_ship_then(
        &self,
        design_id: u64,
fleet_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl order_build_ship for super::RemoteReducers {
    fn order_build_ship_then(
        &self,
        design_id: u64,
fleet_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(OrderBuildShipArgs { design_id, fleet_id,  }, callback)
    }
}

