// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::order_type_type::OrderType;
use super::order_status_type::OrderStatus;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Order {
    pub id: u64,
    pub faction_id: u64,
    pub order_type: OrderType,
    pub status: OrderStatus,
    pub target_id: Option::<u64>,
    pub target_system_id: Option::<u64>,
    pub ship_id: Option::<u64>,
    pub fleet_id: Option::<u64>,
    pub created_tick: u64,
    pub complete_tick: Option::<u64>,
}


impl __sdk::InModule for Order {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `Order`.
///
/// Provides typed access to columns for query building.
pub struct OrderCols {
    pub id: __sdk::__query_builder::Col<Order, u64>,
    pub faction_id: __sdk::__query_builder::Col<Order, u64>,
    pub order_type: __sdk::__query_builder::Col<Order, OrderType>,
    pub status: __sdk::__query_builder::Col<Order, OrderStatus>,
    pub target_id: __sdk::__query_builder::Col<Order, Option::<u64>>,
    pub target_system_id: __sdk::__query_builder::Col<Order, Option::<u64>>,
    pub ship_id: __sdk::__query_builder::Col<Order, Option::<u64>>,
    pub fleet_id: __sdk::__query_builder::Col<Order, Option::<u64>>,
    pub created_tick: __sdk::__query_builder::Col<Order, u64>,
    pub complete_tick: __sdk::__query_builder::Col<Order, Option::<u64>>,
}

impl __sdk::__query_builder::HasCols for Order {
    type Cols = OrderCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        OrderCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            faction_id: __sdk::__query_builder::Col::new(table_name, "faction_id"),
            order_type: __sdk::__query_builder::Col::new(table_name, "order_type"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            target_id: __sdk::__query_builder::Col::new(table_name, "target_id"),
            target_system_id: __sdk::__query_builder::Col::new(table_name, "target_system_id"),
            ship_id: __sdk::__query_builder::Col::new(table_name, "ship_id"),
            fleet_id: __sdk::__query_builder::Col::new(table_name, "fleet_id"),
            created_tick: __sdk::__query_builder::Col::new(table_name, "created_tick"),
            complete_tick: __sdk::__query_builder::Col::new(table_name, "complete_tick"),

        }
    }
}

/// Indexed column accessor struct for the table `Order`.
///
/// Provides typed access to indexed columns for query building.
pub struct OrderIxCols {
    pub faction_id: __sdk::__query_builder::IxCol<Order, u64>,
    pub id: __sdk::__query_builder::IxCol<Order, u64>,
}

impl __sdk::__query_builder::HasIxCols for Order {
    type IxCols = OrderIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        OrderIxCols {
            faction_id: __sdk::__query_builder::IxCol::new(table_name, "faction_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Order {}

