// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct OrderMoveFleetArgs {
    pub fleet_id: u64,
    pub dest_system_id: u64,
}

impl From<OrderMoveFleetArgs> for super::Reducer {
    fn from(args: OrderMoveFleetArgs) -> Self {
        Self::OrderMoveFleet {
            fleet_id: args.fleet_id,
            dest_system_id: args.dest_system_id,
}
}
}

impl __sdk::InModule for OrderMoveFleetArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `order_move_fleet`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait order_move_fleet {
    /// Request that the remote module invoke the reducer `order_move_fleet` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`order_move_fleet:order_move_fleet_then`] to run a callback after the reducer completes.
    fn order_move_fleet(&self, fleet_id: u64,
dest_system_id: u64,
) -> __sdk::Result<()> {
        self.order_move_fleet_then(fleet_id, dest_system_id,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `order_move_fleet` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn order_move_fleet_then(
        &self,
        fleet_id: u64,
dest_system_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl order_move_fleet for super::RemoteReducers {
    fn order_move_fleet_then(
        &self,
        fleet_id: u64,
dest_system_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(OrderMoveFleetArgs { fleet_id, dest_system_id,  }, callback)
    }
}

