// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::block_type_type::BlockType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlaceBlockArgs {
    pub draft_id: u64,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub block_type: BlockType,
    pub rotation: u8,
}

impl From<PlaceBlockArgs> for super::Reducer {
    fn from(args: PlaceBlockArgs) -> Self {
        Self::PlaceBlock {
            draft_id: args.draft_id,
            x: args.x,
            y: args.y,
            z: args.z,
            block_type: args.block_type,
            rotation: args.rotation,
}
}
}

impl __sdk::InModule for PlaceBlockArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `place_block`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait place_block {
    /// Request that the remote module invoke the reducer `place_block` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`place_block:place_block_then`] to run a callback after the reducer completes.
    fn place_block(&self, draft_id: u64,
x: i32,
y: i32,
z: i32,
block_type: BlockType,
rotation: u8,
) -> __sdk::Result<()> {
        self.place_block_then(draft_id, x, y, z, block_type, rotation,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `place_block` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn place_block_then(
        &self,
        draft_id: u64,
x: i32,
y: i32,
z: i32,
block_type: BlockType,
rotation: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl place_block for super::RemoteReducers {
    fn place_block_then(
        &self,
        draft_id: u64,
x: i32,
y: i32,
z: i32,
block_type: BlockType,
rotation: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(PlaceBlockArgs { draft_id, x, y, z, block_type, rotation,  }, callback)
    }
}

