// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Planet {
    pub id: u64,
    pub system_id: u64,
    pub owner_faction_id: Option::<u64>,
    pub population: i64,
    pub minerals_output: i64,
    pub energy_output: i64,
    pub research_output: i64,
}


impl __sdk::InModule for Planet {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `Planet`.
///
/// Provides typed access to columns for query building.
pub struct PlanetCols {
    pub id: __sdk::__query_builder::Col<Planet, u64>,
    pub system_id: __sdk::__query_builder::Col<Planet, u64>,
    pub owner_faction_id: __sdk::__query_builder::Col<Planet, Option::<u64>>,
    pub population: __sdk::__query_builder::Col<Planet, i64>,
    pub minerals_output: __sdk::__query_builder::Col<Planet, i64>,
    pub energy_output: __sdk::__query_builder::Col<Planet, i64>,
    pub research_output: __sdk::__query_builder::Col<Planet, i64>,
}

impl __sdk::__query_builder::HasCols for Planet {
    type Cols = PlanetCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlanetCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            system_id: __sdk::__query_builder::Col::new(table_name, "system_id"),
            owner_faction_id: __sdk::__query_builder::Col::new(table_name, "owner_faction_id"),
            population: __sdk::__query_builder::Col::new(table_name, "population"),
            minerals_output: __sdk::__query_builder::Col::new(table_name, "minerals_output"),
            energy_output: __sdk::__query_builder::Col::new(table_name, "energy_output"),
            research_output: __sdk::__query_builder::Col::new(table_name, "research_output"),

        }
    }
}

/// Indexed column accessor struct for the table `Planet`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlanetIxCols {
    pub id: __sdk::__query_builder::IxCol<Planet, u64>,
    pub system_id: __sdk::__query_builder::IxCol<Planet, u64>,
}

impl __sdk::__query_builder::HasIxCols for Planet {
    type IxCols = PlanetIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlanetIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            system_id: __sdk::__query_builder::IxCol::new(table_name, "system_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Planet {}

