// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::planet_type::Planet;

/// Table handle for the table `planet`.
///
/// Obtain a handle from the [`PlanetTableAccess::planet`] method on [`super::RemoteTables`],
/// like `ctx.db.planet()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.planet().on_insert(...)`.
pub struct PlanetTableHandle<'ctx> {
    imp: __sdk::TableHandle<Planet>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `planet`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlanetTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlanetTableHandle`], which mediates access to the table `planet`.
    fn planet(&self) -> PlanetTableHandle<'_>;
}

impl PlanetTableAccess for super::RemoteTables {
    fn planet(&self) -> PlanetTableHandle<'_> {
        PlanetTableHandle {
            imp: self.imp.get_table::<Planet>("planet"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlanetInsertCallbackId(__sdk::CallbackId);
pub struct PlanetDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlanetTableHandle<'ctx> {
    type Row = Planet;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = Planet> + '_ { self.imp.iter() }

    type InsertCallbackId = PlanetInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlanetInsertCallbackId {
        PlanetInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlanetInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlanetDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlanetDeleteCallbackId {
        PlanetDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlanetDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PlanetUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlanetTableHandle<'ctx> {
    type UpdateCallbackId = PlanetUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlanetUpdateCallbackId {
        PlanetUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlanetUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `id` unique index on the table `planet`,
        /// which allows point queries on the field of the same name
        /// via the [`PlanetIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.planet().id().find(...)`.
        pub struct PlanetIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<Planet, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> PlanetTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `planet`.
            pub fn id(&self) -> PlanetIdUnique<'ctx> {
                PlanetIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> PlanetIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<Planet> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<Planet>("planet");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Planet>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<Planet>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `Planet`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait planetQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `Planet`.
            fn planet(&self) -> __sdk::__query_builder::Table<Planet>;
        }

        impl planetQueryTableAccess for __sdk::QueryTableAccessor {
            fn planet(&self) -> __sdk::__query_builder::Table<Planet> {
                __sdk::__query_builder::Table::new("planet")
            }
        }

