// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::ship_design_draft_type::ShipDesignDraft;

/// Table handle for the table `ship_design_draft`.
///
/// Obtain a handle from the [`ShipDesignDraftTableAccess::ship_design_draft`] method on [`super::RemoteTables`],
/// like `ctx.db.ship_design_draft()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_design_draft().on_insert(...)`.
pub struct ShipDesignDraftTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShipDesignDraft>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ship_design_draft`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShipDesignDraftTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShipDesignDraftTableHandle`], which mediates access to the table `ship_design_draft`.
    fn ship_design_draft(&self) -> ShipDesignDraftTableHandle<'_>;
}

impl ShipDesignDraftTableAccess for super::RemoteTables {
    fn ship_design_draft(&self) -> ShipDesignDraftTableHandle<'_> {
        ShipDesignDraftTableHandle {
            imp: self.imp.get_table::<ShipDesignDraft>("ship_design_draft"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShipDesignDraftInsertCallbackId(__sdk::CallbackId);
pub struct ShipDesignDraftDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShipDesignDraftTableHandle<'ctx> {
    type Row = ShipDesignDraft;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = ShipDesignDraft> + '_ { self.imp.iter() }

    type InsertCallbackId = ShipDesignDraftInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipDesignDraftInsertCallbackId {
        ShipDesignDraftInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShipDesignDraftInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShipDesignDraftDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipDesignDraftDeleteCallbackId {
        ShipDesignDraftDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShipDesignDraftDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ShipDesignDraftUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShipDesignDraftTableHandle<'ctx> {
    type UpdateCallbackId = ShipDesignDraftUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShipDesignDraftUpdateCallbackId {
        ShipDesignDraftUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShipDesignDraftUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `id` unique index on the table `ship_design_draft`,
        /// which allows point queries on the field of the same name
        /// via the [`ShipDesignDraftIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.ship_design_draft().id().find(...)`.
        pub struct ShipDesignDraftIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<ShipDesignDraft, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> ShipDesignDraftTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `ship_design_draft`.
            pub fn id(&self) -> ShipDesignDraftIdUnique<'ctx> {
                ShipDesignDraftIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> ShipDesignDraftIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<ShipDesignDraft> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<ShipDesignDraft>("ship_design_draft");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ShipDesignDraft>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<ShipDesignDraft>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `ShipDesignDraft`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait ship_design_draftQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `ShipDesignDraft`.
            fn ship_design_draft(&self) -> __sdk::__query_builder::Table<ShipDesignDraft>;
        }

        impl ship_design_draftQueryTableAccess for __sdk::QueryTableAccessor {
            fn ship_design_draft(&self) -> __sdk::__query_builder::Table<ShipDesignDraft> {
                __sdk::__query_builder::Table::new("ship_design_draft")
            }
        }

