// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::block_type_type::BlockType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ShipDesignBlock {
    pub id: u64,
    pub design_id: u64,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub block_type: BlockType,
    pub rotation: u8,
}


impl __sdk::InModule for ShipDesignBlock {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `ShipDesignBlock`.
///
/// Provides typed access to columns for query building.
pub struct ShipDesignBlockCols {
    pub id: __sdk::__query_builder::Col<ShipDesignBlock, u64>,
    pub design_id: __sdk::__query_builder::Col<ShipDesignBlock, u64>,
    pub x: __sdk::__query_builder::Col<ShipDesignBlock, i32>,
    pub y: __sdk::__query_builder::Col<ShipDesignBlock, i32>,
    pub z: __sdk::__query_builder::Col<ShipDesignBlock, i32>,
    pub block_type: __sdk::__query_builder::Col<ShipDesignBlock, BlockType>,
    pub rotation: __sdk::__query_builder::Col<ShipDesignBlock, u8>,
}

impl __sdk::__query_builder::HasCols for ShipDesignBlock {
    type Cols = ShipDesignBlockCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ShipDesignBlockCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            design_id: __sdk::__query_builder::Col::new(table_name, "design_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            block_type: __sdk::__query_builder::Col::new(table_name, "block_type"),
            rotation: __sdk::__query_builder::Col::new(table_name, "rotation"),

        }
    }
}

/// Indexed column accessor struct for the table `ShipDesignBlock`.
///
/// Provides typed access to indexed columns for query building.
pub struct ShipDesignBlockIxCols {
    pub design_id: __sdk::__query_builder::IxCol<ShipDesignBlock, u64>,
    pub id: __sdk::__query_builder::IxCol<ShipDesignBlock, u64>,
}

impl __sdk::__query_builder::HasIxCols for ShipDesignBlock {
    type IxCols = ShipDesignBlockIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ShipDesignBlockIxCols {
            design_id: __sdk::__query_builder::IxCol::new(table_name, "design_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ShipDesignBlock {}

