// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::ship_design_draft_block_type::ShipDesignDraftBlock;
use super::block_type_type::BlockType;

/// Table handle for the table `ship_design_draft_block`.
///
/// Obtain a handle from the [`ShipDesignDraftBlockTableAccess::ship_design_draft_block`] method on [`super::RemoteTables`],
/// like `ctx.db.ship_design_draft_block()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_design_draft_block().on_insert(...)`.
pub struct ShipDesignDraftBlockTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShipDesignDraftBlock>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ship_design_draft_block`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShipDesignDraftBlockTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShipDesignDraftBlockTableHandle`], which mediates access to the table `ship_design_draft_block`.
    fn ship_design_draft_block(&self) -> ShipDesignDraftBlockTableHandle<'_>;
}

impl ShipDesignDraftBlockTableAccess for super::RemoteTables {
    fn ship_design_draft_block(&self) -> ShipDesignDraftBlockTableHandle<'_> {
        ShipDesignDraftBlockTableHandle {
            imp: self.imp.get_table::<ShipDesignDraftBlock>("ship_design_draft_block"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShipDesignDraftBlockInsertCallbackId(__sdk::CallbackId);
pub struct ShipDesignDraftBlockDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShipDesignDraftBlockTableHandle<'ctx> {
    type Row = ShipDesignDraftBlock;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = ShipDesignDraftBlock> + '_ { self.imp.iter() }

    type InsertCallbackId = ShipDesignDraftBlockInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipDesignDraftBlockInsertCallbackId {
        ShipDesignDraftBlockInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShipDesignDraftBlockInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShipDesignDraftBlockDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipDesignDraftBlockDeleteCallbackId {
        ShipDesignDraftBlockDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShipDesignDraftBlockDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ShipDesignDraftBlockUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShipDesignDraftBlockTableHandle<'ctx> {
    type UpdateCallbackId = ShipDesignDraftBlockUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShipDesignDraftBlockUpdateCallbackId {
        ShipDesignDraftBlockUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShipDesignDraftBlockUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `id` unique index on the table `ship_design_draft_block`,
        /// which allows point queries on the field of the same name
        /// via the [`ShipDesignDraftBlockIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.ship_design_draft_block().id().find(...)`.
        pub struct ShipDesignDraftBlockIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<ShipDesignDraftBlock, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> ShipDesignDraftBlockTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `ship_design_draft_block`.
            pub fn id(&self) -> ShipDesignDraftBlockIdUnique<'ctx> {
                ShipDesignDraftBlockIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> ShipDesignDraftBlockIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<ShipDesignDraftBlock> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<ShipDesignDraftBlock>("ship_design_draft_block");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ShipDesignDraftBlock>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<ShipDesignDraftBlock>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `ShipDesignDraftBlock`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait ship_design_draft_blockQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `ShipDesignDraftBlock`.
            fn ship_design_draft_block(&self) -> __sdk::__query_builder::Table<ShipDesignDraftBlock>;
        }

        impl ship_design_draft_blockQueryTableAccess for __sdk::QueryTableAccessor {
            fn ship_design_draft_block(&self) -> __sdk::__query_builder::Table<ShipDesignDraftBlock> {
                __sdk::__query_builder::Table::new("ship_design_draft_block")
            }
        }

