// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::block_type_type::BlockType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ShipDesignDraftBlock {
    pub id: u64,
    pub draft_id: u64,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub block_type: BlockType,
    pub rotation: u8,
}


impl __sdk::InModule for ShipDesignDraftBlock {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `ShipDesignDraftBlock`.
///
/// Provides typed access to columns for query building.
pub struct ShipDesignDraftBlockCols {
    pub id: __sdk::__query_builder::Col<ShipDesignDraftBlock, u64>,
    pub draft_id: __sdk::__query_builder::Col<ShipDesignDraftBlock, u64>,
    pub x: __sdk::__query_builder::Col<ShipDesignDraftBlock, i32>,
    pub y: __sdk::__query_builder::Col<ShipDesignDraftBlock, i32>,
    pub z: __sdk::__query_builder::Col<ShipDesignDraftBlock, i32>,
    pub block_type: __sdk::__query_builder::Col<ShipDesignDraftBlock, BlockType>,
    pub rotation: __sdk::__query_builder::Col<ShipDesignDraftBlock, u8>,
}

impl __sdk::__query_builder::HasCols for ShipDesignDraftBlock {
    type Cols = ShipDesignDraftBlockCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ShipDesignDraftBlockCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            draft_id: __sdk::__query_builder::Col::new(table_name, "draft_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            block_type: __sdk::__query_builder::Col::new(table_name, "block_type"),
            rotation: __sdk::__query_builder::Col::new(table_name, "rotation"),

        }
    }
}

/// Indexed column accessor struct for the table `ShipDesignDraftBlock`.
///
/// Provides typed access to indexed columns for query building.
pub struct ShipDesignDraftBlockIxCols {
    pub draft_id: __sdk::__query_builder::IxCol<ShipDesignDraftBlock, u64>,
    pub id: __sdk::__query_builder::IxCol<ShipDesignDraftBlock, u64>,
}

impl __sdk::__query_builder::HasIxCols for ShipDesignDraftBlock {
    type IxCols = ShipDesignDraftBlockIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ShipDesignDraftBlockIxCols {
            draft_id: __sdk::__query_builder::IxCol::new(table_name, "draft_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ShipDesignDraftBlock {}

