// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::ship_design_type::ShipDesign;

/// Table handle for the table `ship_design`.
///
/// Obtain a handle from the [`ShipDesignTableAccess::ship_design`] method on [`super::RemoteTables`],
/// like `ctx.db.ship_design()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_design().on_insert(...)`.
pub struct ShipDesignTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShipDesign>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ship_design`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShipDesignTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShipDesignTableHandle`], which mediates access to the table `ship_design`.
    fn ship_design(&self) -> ShipDesignTableHandle<'_>;
}

impl ShipDesignTableAccess for super::RemoteTables {
    fn ship_design(&self) -> ShipDesignTableHandle<'_> {
        ShipDesignTableHandle {
            imp: self.imp.get_table::<ShipDesign>("ship_design"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShipDesignInsertCallbackId(__sdk::CallbackId);
pub struct ShipDesignDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShipDesignTableHandle<'ctx> {
    type Row = ShipDesign;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = ShipDesign> + '_ { self.imp.iter() }

    type InsertCallbackId = ShipDesignInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipDesignInsertCallbackId {
        ShipDesignInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShipDesignInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShipDesignDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipDesignDeleteCallbackId {
        ShipDesignDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShipDesignDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ShipDesignUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShipDesignTableHandle<'ctx> {
    type UpdateCallbackId = ShipDesignUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShipDesignUpdateCallbackId {
        ShipDesignUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShipDesignUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `id` unique index on the table `ship_design`,
        /// which allows point queries on the field of the same name
        /// via the [`ShipDesignIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.ship_design().id().find(...)`.
        pub struct ShipDesignIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<ShipDesign, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> ShipDesignTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `ship_design`.
            pub fn id(&self) -> ShipDesignIdUnique<'ctx> {
                ShipDesignIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> ShipDesignIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<ShipDesign> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<ShipDesign>("ship_design");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ShipDesign>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<ShipDesign>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `ShipDesign`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait ship_designQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `ShipDesign`.
            fn ship_design(&self) -> __sdk::__query_builder::Table<ShipDesign>;
        }

        impl ship_designQueryTableAccess for __sdk::QueryTableAccessor {
            fn ship_design(&self) -> __sdk::__query_builder::Table<ShipDesign> {
                __sdk::__query_builder::Table::new("ship_design")
            }
        }

