// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Ship {
    pub id: u64,
    pub design_id: u64,
    pub faction_id: u64,
    pub system_id: u64,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub hp: i64,
    pub fuel: i64,
}


impl __sdk::InModule for Ship {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `Ship`.
///
/// Provides typed access to columns for query building.
pub struct ShipCols {
    pub id: __sdk::__query_builder::Col<Ship, u64>,
    pub design_id: __sdk::__query_builder::Col<Ship, u64>,
    pub faction_id: __sdk::__query_builder::Col<Ship, u64>,
    pub system_id: __sdk::__query_builder::Col<Ship, u64>,
    pub x: __sdk::__query_builder::Col<Ship, f32>,
    pub y: __sdk::__query_builder::Col<Ship, f32>,
    pub z: __sdk::__query_builder::Col<Ship, f32>,
    pub hp: __sdk::__query_builder::Col<Ship, i64>,
    pub fuel: __sdk::__query_builder::Col<Ship, i64>,
}

impl __sdk::__query_builder::HasCols for Ship {
    type Cols = ShipCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ShipCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            design_id: __sdk::__query_builder::Col::new(table_name, "design_id"),
            faction_id: __sdk::__query_builder::Col::new(table_name, "faction_id"),
            system_id: __sdk::__query_builder::Col::new(table_name, "system_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            hp: __sdk::__query_builder::Col::new(table_name, "hp"),
            fuel: __sdk::__query_builder::Col::new(table_name, "fuel"),

        }
    }
}

/// Indexed column accessor struct for the table `Ship`.
///
/// Provides typed access to indexed columns for query building.
pub struct ShipIxCols {
    pub faction_id: __sdk::__query_builder::IxCol<Ship, u64>,
    pub id: __sdk::__query_builder::IxCol<Ship, u64>,
    pub system_id: __sdk::__query_builder::IxCol<Ship, u64>,
}

impl __sdk::__query_builder::HasIxCols for Ship {
    type IxCols = ShipIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ShipIxCols {
            faction_id: __sdk::__query_builder::IxCol::new(table_name, "faction_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            system_id: __sdk::__query_builder::IxCol::new(table_name, "system_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Ship {}

