// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::ship_design_block_type::ShipDesignBlock;
use super::block_type_type::BlockType;

/// Table handle for the table `ship_design_block`.
///
/// Obtain a handle from the [`ShipDesignBlockTableAccess::ship_design_block`] method on [`super::RemoteTables`],
/// like `ctx.db.ship_design_block()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_design_block().on_insert(...)`.
pub struct ShipDesignBlockTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShipDesignBlock>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ship_design_block`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShipDesignBlockTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShipDesignBlockTableHandle`], which mediates access to the table `ship_design_block`.
    fn ship_design_block(&self) -> ShipDesignBlockTableHandle<'_>;
}

impl ShipDesignBlockTableAccess for super::RemoteTables {
    fn ship_design_block(&self) -> ShipDesignBlockTableHandle<'_> {
        ShipDesignBlockTableHandle {
            imp: self.imp.get_table::<ShipDesignBlock>("ship_design_block"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShipDesignBlockInsertCallbackId(__sdk::CallbackId);
pub struct ShipDesignBlockDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShipDesignBlockTableHandle<'ctx> {
    type Row = ShipDesignBlock;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = ShipDesignBlock> + '_ { self.imp.iter() }

    type InsertCallbackId = ShipDesignBlockInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipDesignBlockInsertCallbackId {
        ShipDesignBlockInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShipDesignBlockInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShipDesignBlockDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipDesignBlockDeleteCallbackId {
        ShipDesignBlockDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShipDesignBlockDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ShipDesignBlockUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShipDesignBlockTableHandle<'ctx> {
    type UpdateCallbackId = ShipDesignBlockUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShipDesignBlockUpdateCallbackId {
        ShipDesignBlockUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShipDesignBlockUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `id` unique index on the table `ship_design_block`,
        /// which allows point queries on the field of the same name
        /// via the [`ShipDesignBlockIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.ship_design_block().id().find(...)`.
        pub struct ShipDesignBlockIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<ShipDesignBlock, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> ShipDesignBlockTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `ship_design_block`.
            pub fn id(&self) -> ShipDesignBlockIdUnique<'ctx> {
                ShipDesignBlockIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> ShipDesignBlockIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<ShipDesignBlock> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<ShipDesignBlock>("ship_design_block");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ShipDesignBlock>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<ShipDesignBlock>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `ShipDesignBlock`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait ship_design_blockQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `ShipDesignBlock`.
            fn ship_design_block(&self) -> __sdk::__query_builder::Table<ShipDesignBlock>;
        }

        impl ship_design_blockQueryTableAccess for __sdk::QueryTableAccessor {
            fn ship_design_block(&self) -> __sdk::__query_builder::Table<ShipDesignBlock> {
                __sdk::__query_builder::Table::new("ship_design_block")
            }
        }

