// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ShipDesign {
    pub id: u64,
    pub faction_id: u64,
    pub name: String,
    pub total_mass: f32,
    pub total_cost: i64,
    pub max_hp: i64,
    pub thrust: f32,
    pub attack: i64,
    pub block_count: i32,
    pub created_tick: u64,
}


impl __sdk::InModule for ShipDesign {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `ShipDesign`.
///
/// Provides typed access to columns for query building.
pub struct ShipDesignCols {
    pub id: __sdk::__query_builder::Col<ShipDesign, u64>,
    pub faction_id: __sdk::__query_builder::Col<ShipDesign, u64>,
    pub name: __sdk::__query_builder::Col<ShipDesign, String>,
    pub total_mass: __sdk::__query_builder::Col<ShipDesign, f32>,
    pub total_cost: __sdk::__query_builder::Col<ShipDesign, i64>,
    pub max_hp: __sdk::__query_builder::Col<ShipDesign, i64>,
    pub thrust: __sdk::__query_builder::Col<ShipDesign, f32>,
    pub attack: __sdk::__query_builder::Col<ShipDesign, i64>,
    pub block_count: __sdk::__query_builder::Col<ShipDesign, i32>,
    pub created_tick: __sdk::__query_builder::Col<ShipDesign, u64>,
}

impl __sdk::__query_builder::HasCols for ShipDesign {
    type Cols = ShipDesignCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ShipDesignCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            faction_id: __sdk::__query_builder::Col::new(table_name, "faction_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            total_mass: __sdk::__query_builder::Col::new(table_name, "total_mass"),
            total_cost: __sdk::__query_builder::Col::new(table_name, "total_cost"),
            max_hp: __sdk::__query_builder::Col::new(table_name, "max_hp"),
            thrust: __sdk::__query_builder::Col::new(table_name, "thrust"),
            attack: __sdk::__query_builder::Col::new(table_name, "attack"),
            block_count: __sdk::__query_builder::Col::new(table_name, "block_count"),
            created_tick: __sdk::__query_builder::Col::new(table_name, "created_tick"),

        }
    }
}

/// Indexed column accessor struct for the table `ShipDesign`.
///
/// Provides typed access to indexed columns for query building.
pub struct ShipDesignIxCols {
    pub faction_id: __sdk::__query_builder::IxCol<ShipDesign, u64>,
    pub id: __sdk::__query_builder::IxCol<ShipDesign, u64>,
}

impl __sdk::__query_builder::HasIxCols for ShipDesign {
    type IxCols = ShipDesignIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ShipDesignIxCols {
            faction_id: __sdk::__query_builder::IxCol::new(table_name, "faction_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ShipDesign {}

