// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ShipDesignDraft {
    pub id: u64,
    pub faction_id: u64,
    pub name: String,
    pub updated_at: __sdk::Timestamp,
}


impl __sdk::InModule for ShipDesignDraft {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `ShipDesignDraft`.
///
/// Provides typed access to columns for query building.
pub struct ShipDesignDraftCols {
    pub id: __sdk::__query_builder::Col<ShipDesignDraft, u64>,
    pub faction_id: __sdk::__query_builder::Col<ShipDesignDraft, u64>,
    pub name: __sdk::__query_builder::Col<ShipDesignDraft, String>,
    pub updated_at: __sdk::__query_builder::Col<ShipDesignDraft, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ShipDesignDraft {
    type Cols = ShipDesignDraftCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ShipDesignDraftCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            faction_id: __sdk::__query_builder::Col::new(table_name, "faction_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),

        }
    }
}

/// Indexed column accessor struct for the table `ShipDesignDraft`.
///
/// Provides typed access to indexed columns for query building.
pub struct ShipDesignDraftIxCols {
    pub faction_id: __sdk::__query_builder::IxCol<ShipDesignDraft, u64>,
    pub id: __sdk::__query_builder::IxCol<ShipDesignDraft, u64>,
}

impl __sdk::__query_builder::HasIxCols for ShipDesignDraft {
    type IxCols = ShipDesignDraftIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ShipDesignDraftIxCols {
            faction_id: __sdk::__query_builder::IxCol::new(table_name, "faction_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ShipDesignDraft {}

