// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::sim_run_type::SimRun;

/// Table handle for the table `sim_run`.
///
/// Obtain a handle from the [`SimRunTableAccess::sim_run`] method on [`super::RemoteTables`],
/// like `ctx.db.sim_run()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sim_run().on_insert(...)`.
pub struct SimRunTableHandle<'ctx> {
    imp: __sdk::TableHandle<SimRun>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sim_run`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SimRunTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SimRunTableHandle`], which mediates access to the table `sim_run`.
    fn sim_run(&self) -> SimRunTableHandle<'_>;
}

impl SimRunTableAccess for super::RemoteTables {
    fn sim_run(&self) -> SimRunTableHandle<'_> {
        SimRunTableHandle {
            imp: self.imp.get_table::<SimRun>("sim_run"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SimRunInsertCallbackId(__sdk::CallbackId);
pub struct SimRunDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SimRunTableHandle<'ctx> {
    type Row = SimRun;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = SimRun> + '_ { self.imp.iter() }

    type InsertCallbackId = SimRunInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimRunInsertCallbackId {
        SimRunInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SimRunInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SimRunDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimRunDeleteCallbackId {
        SimRunDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SimRunDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SimRunUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SimRunTableHandle<'ctx> {
    type UpdateCallbackId = SimRunUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SimRunUpdateCallbackId {
        SimRunUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SimRunUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `run_id` unique index on the table `sim_run`,
        /// which allows point queries on the field of the same name
        /// via the [`SimRunRunIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.sim_run().run_id().find(...)`.
        pub struct SimRunRunIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<SimRun, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> SimRunTableHandle<'ctx> {
            /// Get a handle on the `run_id` unique index on the table `sim_run`.
            pub fn run_id(&self) -> SimRunRunIdUnique<'ctx> {
                SimRunRunIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("run_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> SimRunRunIdUnique<'ctx> {
            /// Find the subscribed row whose `run_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<SimRun> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<SimRun>("sim_run");
    _table.add_unique_constraint::<u64>("run_id", |row| &row.run_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SimRun>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<SimRun>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `SimRun`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait sim_runQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `SimRun`.
            fn sim_run(&self) -> __sdk::__query_builder::Table<SimRun>;
        }

        impl sim_runQueryTableAccess for __sdk::QueryTableAccessor {
            fn sim_run(&self) -> __sdk::__query_builder::Table<SimRun> {
                __sdk::__query_builder::Table::new("sim_run")
            }
        }

