// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimRun {
    pub run_id: u64,
    pub requested_ticks: u64,
    pub from_tick: u64,
    pub to_tick: u64,
    pub completed_at: __sdk::Timestamp,
}


impl __sdk::InModule for SimRun {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `SimRun`.
///
/// Provides typed access to columns for query building.
pub struct SimRunCols {
    pub run_id: __sdk::__query_builder::Col<SimRun, u64>,
    pub requested_ticks: __sdk::__query_builder::Col<SimRun, u64>,
    pub from_tick: __sdk::__query_builder::Col<SimRun, u64>,
    pub to_tick: __sdk::__query_builder::Col<SimRun, u64>,
    pub completed_at: __sdk::__query_builder::Col<SimRun, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for SimRun {
    type Cols = SimRunCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimRunCols {
            run_id: __sdk::__query_builder::Col::new(table_name, "run_id"),
            requested_ticks: __sdk::__query_builder::Col::new(table_name, "requested_ticks"),
            from_tick: __sdk::__query_builder::Col::new(table_name, "from_tick"),
            to_tick: __sdk::__query_builder::Col::new(table_name, "to_tick"),
            completed_at: __sdk::__query_builder::Col::new(table_name, "completed_at"),

        }
    }
}

/// Indexed column accessor struct for the table `SimRun`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimRunIxCols {
    pub run_id: __sdk::__query_builder::IxCol<SimRun, u64>,
}

impl __sdk::__query_builder::HasIxCols for SimRun {
    type IxCols = SimRunIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimRunIxCols {
            run_id: __sdk::__query_builder::IxCol::new(table_name, "run_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimRun {}

