// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::star_system_type::StarSystem;

/// Table handle for the table `star_system`.
///
/// Obtain a handle from the [`StarSystemTableAccess::star_system`] method on [`super::RemoteTables`],
/// like `ctx.db.star_system()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.star_system().on_insert(...)`.
pub struct StarSystemTableHandle<'ctx> {
    imp: __sdk::TableHandle<StarSystem>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `star_system`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StarSystemTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StarSystemTableHandle`], which mediates access to the table `star_system`.
    fn star_system(&self) -> StarSystemTableHandle<'_>;
}

impl StarSystemTableAccess for super::RemoteTables {
    fn star_system(&self) -> StarSystemTableHandle<'_> {
        StarSystemTableHandle {
            imp: self.imp.get_table::<StarSystem>("star_system"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StarSystemInsertCallbackId(__sdk::CallbackId);
pub struct StarSystemDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for StarSystemTableHandle<'ctx> {
    type Row = StarSystem;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = StarSystem> + '_ { self.imp.iter() }

    type InsertCallbackId = StarSystemInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StarSystemInsertCallbackId {
        StarSystemInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StarSystemInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StarSystemDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StarSystemDeleteCallbackId {
        StarSystemDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StarSystemDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct StarSystemUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StarSystemTableHandle<'ctx> {
    type UpdateCallbackId = StarSystemUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StarSystemUpdateCallbackId {
        StarSystemUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StarSystemUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `id` unique index on the table `star_system`,
        /// which allows point queries on the field of the same name
        /// via the [`StarSystemIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.star_system().id().find(...)`.
        pub struct StarSystemIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<StarSystem, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> StarSystemTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `star_system`.
            pub fn id(&self) -> StarSystemIdUnique<'ctx> {
                StarSystemIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> StarSystemIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<StarSystem> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<StarSystem>("star_system");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<StarSystem>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<StarSystem>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `StarSystem`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait star_systemQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `StarSystem`.
            fn star_system(&self) -> __sdk::__query_builder::Table<StarSystem>;
        }

        impl star_systemQueryTableAccess for __sdk::QueryTableAccessor {
            fn star_system(&self) -> __sdk::__query_builder::Table<StarSystem> {
                __sdk::__query_builder::Table::new("star_system")
            }
        }

